name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Set up Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable


    #- name: Install Chrome
      #run: |
        #sudo apt-get update
        #sudo apt-get install -y google-chrome-stable

    #- name: Get Chrome Version
      #id: chrome-version
      #run: |
        #CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        #echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

   # - name: Install ChromeDriver
      #run: |
       # CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+' | cut -d '.' -f 1,2)
        #CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        #curl -sS -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        #unzip chromedriver_linux64.zip
        #sudo mv chromedriver /usr/local/bin/chromedriver
        #sudo chmod +x /usr/local/bin/chromedriver

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Clear Maven Cache
      run: mvn dependency:purge-local-repository

    - name: Build and Install Dependencies
      run: mvn clean install -X

    - name: Package the Project
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
